onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - pre-commit
  - spawn-sync
  - svelte-preprocess

overrides:
  cookie@<0.7.0: '>=0.7.0'
  cross-spawn@<6.0.6: '>=6.0.6'
